from enum import Enum


class routers(Enum):
    #principal
    PRINCIPAL="/principal"
    REGLAS_JUEGO_UNO=f"/{PRINCIPAL}/reglas_juego_uno"
    JUEGO_UNO=f"/{PRINCIPAL}/piedra_papel_tijeras_lagarto_spock"
    JUEGO_DOS=f"/{PRINCIPAL}/Encuentra_el_numero"
    JUEGO_TRES=f"/{REGLAS_JUEGO_UNO}/3_en_rayas"

    #secundarias
    JUEGO_UNO_FIN_DEL_JUEGO_PERDISTES = f"/{JUEGO_UNO}/PERDISTES"
    JUEGO_UNO_FIN_DEL_JUEGO_GANASTES = f"/{JUEGO_UNO}/GANASTES"
    JUEGO_DOS_FIN_DEL_JUEGO_PERDISTES = f"/{JUEGO_DOS}/PERDISTES"
    JUEGO_DOS_FIN_DEL_JUEGO_GANASTES = f"/{JUEGO_DOS}/GANASTES"
    JUEGO_TRES_FIN_DEL_JUEGO_PERDISTES = f"/{JUEGO_TRES}/PERDISTES"
    JUEGO_TRES_FIN_DEL_JUEGO_GANASTES = f"/{JUEGO_TRES}/GANASTES"

